name: Deploy Dioxus Site to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: self-hosted

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --release -- -D warnings

      - name: Install Cargo Audit
        run: cargo install cargo-audit

      - name: Run Vulnerability Scan
        run: cargo audit

      - name: Build Dioxus App
        run: dx build --release

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/dx/nomadlibre-website/release/web/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
